function Roulette() {
  	return (
    <>
	<div id="container" className="">
		<div className="flex justify-start items-center rounded-lg w-full relative translate-x-[-350rem]">
			{
				[
					{color: "yellow", number: "K"},
					{color: "red", number: "1"},
					{color: "black", number: "8"},
					{color: "red", number: "2"},
					{color: "black", number: "9"},
					{color: "red", number: "3"},
					{color: "black", number: "10"},
					{color: "red", number: "4"},
					{color: "black", number: "11"},
					{color: "red", number: "5"},
					{color: "black", number: "12"},
					{color: "red", number: "6"},
					{color: "black", number: "13"},
					{color: "red", number: "7"},
					{color: "black", number: "14"},
					{color: "yellow", number: "K"},
					{color: "red", number: "1"},
					{color: "black", number: "8"},
					{color: "red", number: "2"},
					{color: "black", number: "9"},
					{color: "red", number: "3"},
					{color: "black", number: "10"},
					{color: "red", number: "4"},
					{color: "black", number: "11"},
					{color: "red", number: "5"},
					{color: "black", number: "12"},
					{color: "red", number: "6"},
					{color: "black", number: "13"},
					{color: "red", number: "7"},
					{color: "black", number: "14"},
					{color: "yellow", number: "K"},
					{color: "red", number: "1"},
					{color: "black", number: "8"},
					{color: "red", number: "2"},
					{color: "black", number: "9"},
					{color: "red", number: "3"},
					{color: "black", number: "10"},
					{color: "red", number: "4"},
					{color: "black", number: "11"},
					{color: "red", number: "5"},
					{color: "black", number: "12"},
					{color: "red", number: "6"},
					{color: "black", number: "13"},
					{color: "red", number: "7"},
					{color: "black", number: "14"},
					{color: "yellow", number: "K"},
					{color: "red", number: "1"},
					{color: "black", number: "8"},
					{color: "red", number: "2"},
					{color: "black", number: "9"},
					{color: "red", number: "3"},
					{color: "black", number: "10"},
					{color: "red", number: "4"},
					{color: "black", number: "11"},
					{color: "red", number: "5"},
					{color: "black", number: "12"},
					{color: "red", number: "6"},
					{color: "black", number: "13"},
					{color: "red", number: "7"},
					{color: "black", number: "14"},
					{color: "yellow", number: "K"},
					{color: "red", number: "1"},
					{color: "black", number: "8"},
					{color: "red", number: "2"},
					{color: "black", number: "9"},
					{color: "red", number: "3"},
					{color: "black", number: "10"},
					{color: "red", number: "4"},
					{color: "black", number: "11"},
					{color: "red", number: "5"},
					{color: "black", number: "12"},
					{color: "red", number: "6"},
					{color: "black", number: "13"},
					{color: "red", number: "7"},
					{color: "black", number: "14"},
					{color: "yellow", number: "K"},
					{color: "red", number: "1"},
					{color: "black", number: "8"},
					{color: "red", number: "2"},
					{color: "black", number: "9"},
					{color: "red", number: "3"},
					{color: "black", number: "10"},
					{color: "red", number: "4"},
					{color: "black", number: "11"},
					{color: "red", number: "5"},
					{color: "black", number: "12"},
					{color: "red", number: "6"},
					{color: "black", number: "13"},
					{color: "red", number: "7"},
					{color: "black", number: "14"},
					{color: "yellow", number: "K"},
					{color: "red", number: "1"},
					{color: "black", number: "8"},
					{color: "red", number: "2"},
					{color: "black", number: "9"},
					{color: "red", number: "3"},
					{color: "black", number: "10"},
					{color: "red", number: "4"},
					{color: "black", number: "11"},
					{color: "red", number: "5"},
					{color: "black", number: "12"},
					{color: "red", number: "6"},
					{color: "black", number: "13"},
					{color: "red", number: "7"},
					{color: "black", number: "14"},
					{color: "yellow", number: "K"},
					{color: "red", number: "1"},
					{color: "black", number: "8"},
					{color: "red", number: "2"},
					{color: "black", number: "9"},
					{color: "red", number: "3"},
					{color: "black", number: "10"},
					{color: "red", number: "4"},
					{color: "black", number: "11"},
					{color: "red", number: "5"},
					{color: "black", number: "12"},
					{color: "red", number: "6"},
					{color: "black", number: "13"},
					{color: "red", number: "7"},
					{color: "black", number: "14"},
					{color: "yellow", number: "K"},
					{color: "red", number: "1"},
					{color: "black", number: "8"},
					{color: "red", number: "2"},
					{color: "black", number: "9"},
					{color: "red", number: "3"},
					{color: "black", number: "10"},
					{color: "red", number: "4"},
					{color: "black", number: "11"},
					{color: "red", number: "5"},
					{color: "black", number: "12"},
					{color: "red", number: "6"},
					{color: "black", number: "13"},
					{color: "red", number: "7"},
					{color: "black", number: "14"},
					{color: "yellow", number: "K"},
					{color: "red", number: "1"},
					{color: "black", number: "8"},
					{color: "red", number: "2"},
					{color: "black", number: "9"},
					{color: "red", number: "3"},
					{color: "black", number: "10"},
					{color: "red", number: "4"},
					{color: "black", number: "11"},
					{color: "red", number: "5"},
					{color: "black", number: "12"},
					{color: "red", number: "6"},
					{color: "black", number: "13"},
					{color: "red", number: "7"},
					{color: "black", number: "14"},
				].map((div, index) => (
					<div key={index} className={`
						w-28 h-28 
						${div.color == "yellow" ? "bg-yellow-500" : div.color == "red" ? "bg-red-500" : "bg-black"} 
						text-3xl text-${div.number === "K" ? "[#181818]" : "[#e6e6e6]"} font-bold
						flex flex-shrink-0 justify-center items-center select-none`}
					>{div.number}</div>
				))
			}
		</div>
	</div>
    </>
  	);
}

export {Roulette};
